apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: t4hub-config-pvc
  labels:
    app: t4hub
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: t4hub-ebs-gp3
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-pvc
  labels:
    app: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: t4hub-ebs-gp3
  resources:
    requests:
      storage: 20Gi
