apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-{{container_name}}
  labels:
    app: {{app_label}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app-user: {{container_name}}
  template:
    metadata:
      labels:
        app: {{app_label}}
        app-user: {{container_name}}
    spec:
      volumes:
{{container_vols}}
        - name: config
          hostPath:
            path: {{mount_nfs_base}}/config-apphub
            type: Directory
      containers:
      - name: {{container_name}}
        image: {{image_name}}
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "{{patches}}"]
        securityContext:
          runAsUser: 0
        resources:
{{limits}}
          requests:
{{cpu_requested}}
        env:
        - name: VNC_DISABLE_AUTH
          value: "true"
        - name: VNC_ALLOW_CLIENT_TO_OVERRIDE_VNC_SETTINGS
          value: "true"
        volumeMounts:
          - name: config
            mountPath: /etc/kasmvnc/
{{container_vol_mounts}}
        ports:
        - containerPort: 6901
        - containerPort: 8085
{{gpu_toleration}}