apiVersion: apps/v1
kind: Deployment
metadata:
  name: t4-{{ container_name }}
  labels:
    app: t4-novnc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t4-novnc
  template:
    metadata:
      labels:
        app: t4-novnc
    spec:
      containers:
      - name: nginx
        image: 474930672109.dkr.ecr.eu-west-1.amazonaws.com/nextgendem-mac/t4-novnc:0.9
        env:
        - name: VNCOPTIONS
          value: -disableBasicAuth
        - name: KASM_PORT
          value: "6901"
        ports:
        - containerPort: 6901
          name: kasmvnc
        volumeMounts:
        - mountPath: /home/kasm-user/.vnc/kasmvnc.yaml
          name: kasmvnc-config
          subPath: kasmvnc.yaml
      securityContext:
        runAsUser: 0
      volumes:
      - name: kasmvnc-config
        configMap:
          name: t4-novnc-config