version: "3.3"

services:

  t4-hub:
    image: opendx/t4hub
    container_name: ${T4HUB_NAME}
    build:
      context: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./proxy/nginx.conf:/app/proxy/nginx.conf
      - transformer4-hub-volume:/srv
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

  proxy:
    image: opendx/nginx
    container_name: ${NGINX_NAME}
    build:
      context: ./proxy
    depends_on:
      - t4-hub
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    command: [ nginx-debug, '-g', 'daemon off;' ]

volumes:
  transformer4-hub-volume:
