[supervisord]
nodaemon=true

[program:apphub]
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
command=/usr/local/bin/gunicorn --reload --workers 5 --timeout 120 --worker-class uvicorn.workers.UvicornWorker -c /app/apphub/gunicorn_config.py --bind 0.0.0.0:8080 apphub.main:app
directory=/app
user=root
process_name=app-hub
numprocs=1
autostart=true
autorestart=true
redirect_stderr=True
