
user www-data;

events {
}

http {
  sub_filter_types text/html text/css application/javascript;
  log_format custom '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$uri" "$http_x_forwarded_for" "$request_filename"';
  server {
    listen     80;
    server_name  localhost;
    access_log /var/log/nginx/access2.log custom;
    error_log  /var/log/nginx/error2.log  debug;

    location / {
      proxy_pass http://172.18.0.2:8080;
      proxy_connect_timeout 300s;
      proxy_read_timeout 600s;      
    }
    

    location /49c26cc3-06ec-4ae7-830c-4430f7f97c52/ {
        proxy_pass http://172.18.0.4:6901/;          
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;    
        proxy_http_version 1.1;        
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        add_header Cache-Control no-cache;        
    }
    
    location /49c26cc3-06ec-4ae7-830c-4430f7f97c52-files/ {
        proxy_pass http://172.18.0.4:8085/;
        sub_filter 'href="/'  'href="/49c26cc3-06ec-4ae7-830c-4430f7f97c52-files/';
        sub_filter 'src="/'  'src="/49c26cc3-06ec-4ae7-830c-4430f7f97c52-files/';
        sub_filter_once off;

        proxy_set_header Host $host;
        client_max_body_size 100M;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme; 
    }    


  }
}
