apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

patches:
  - path: patch-apphub-pod.yaml
  - path: patch-postgresql.yaml
  - path: patch-service.yaml
